{% set name = "pyhanko-certvalidator" %}
{% set version = "0.26.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyhanko-certvalidator-{{ version }}.tar.gz
  sha256: 47fba8e9dbf846d766f2e0a453572dd4b25b2f1397847a31fe892c8eb00391f5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - asn1crypto >=1.5.0
    - cryptography >=3.3.1
    - oscrypto >=1.1.0
    - requests >=2.24.0
    - uritools >=3.0.1

test:
  imports:
    - pyhanko_certvalidator
    - pyhanko_certvalidator.fetchers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MatthiasValvekens/certvalidator
  summary: Validates X.509 certificates and paths; forked from wbond/certvalidator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
